### ISSUE TITLE
inventory cant be closed

### ISSUE THREAD

**Issue by icaofficial** [marinogabri/vrp_inventoryhud#12]
Inventory cant be closed after opened up..

**Comment by marinogabri** [comment]
> Inventory cant be closed after opened up..

Did you change resource name?

**Comment by icaofficial** [comment]
yea in vrp_inventory, should i name it back vrp_inventoryhud_main?

**Comment by icaofficial** [comment]
i did it, tryied vrp_invetoryhud and vrp_inventoryhud-master still dont work..

**Comment by marinogabri** [comment]
Which key are you using to close it? And which layout do you use?
